M48
; DRILL file {KiCad 8.0.5} date 2025-06-09T13:31:49+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-09T13:31:49+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0295
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0425
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1260
%
G90
G05
T1
X6.5108Y-3.7382
T2
X5.7992Y-3.6841
X5.7992Y-3.7923
T3
X6.8258Y-3.7382
T4
X4.5276Y-3.734
X7.086Y-3.734
M30
